export enum UserRole {
  STUDENT = 'STUDENT',
  ADMIN = 'ADMIN'
}

export enum MatchPurpose {
  STUDY = 'Study Partner',
  GYM = 'Gym Buddy',
  HANGOUT = 'Social Hangout',
  PROJECT = 'Project Collaborator'
}

export enum MatchStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED'
}

export enum ReportStatus {
  PENDING = 'PENDING',
  REVIEWED = 'REVIEWED',
  RESOLVED = 'RESOLVED',
  DISMISSED = 'DISMISSED'
}

export interface User {
  id: string;
  email: string; // Must be @aui.ma
  passwordHash: string; // Store hashed password
  fullName: string;
  major: string;
  yearOfStudy: string;
  role: UserRole;
  profilePic?: string;
  purposes: MatchPurpose[];
  interests: string[];
  bio?: string;
  isVerified: boolean;
  reportsCount: number;
  isBanned: boolean;
  createdAt: string;
}

export interface MatchRequest {
  id: string;
  senderId: string;
  receiverId: string;
  purpose: MatchPurpose;
  status: MatchStatus;
  aiReasoning?: string; // Generated by Gemini
  createdAt: string;
}

export interface Message {
  id: string;
  matchId: string;
  senderId: string;
  content: string;
  timestamp: string;
  read: boolean;
}

export interface Report {
  id: string;
  reporterId: string;
  reportedUserId: string;
  reason: string;
  description: string;
  timestamp: string;
  status: ReportStatus;
}

export interface Notification {
  id: string;
  userId: string;
  type: 'MATCH_REQUEST' | 'MATCH_ACCEPTED' | 'MESSAGE';
  title: string;
  message: string;
  relatedId: string; // matchId or userId
  read: boolean;
  createdAt: string;
}